[package]
name = "persistence-clickhouse"
version = "0.1.0"
edition = "2024"

[lib]
name = "persistence_clickhouse"
path = "src/lib.rs"

[dependencies]
event-core = { path = "../event-core" }
persistence-core = { path = "../persistence-core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "2.12"
vision-core = { path = "../vision-core" }
